name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: alpine:3.11.11@sha256:71a2b866473e26e7c3dfcd7488975ed8d8ba46c495f76a50957fc11f2d6f4dec

    steps:
    - uses: actions/checkout@v2

    - name: fetch prerequisites
      run: |
        apk add --no-cache \
          coreutils \
          curl \
          gcc \
          make \
          musl-dev \
          openssl-dev

    - name: fetch source
      run: |
        set -ex

        DOWNLOADURL=https://github.com/redis/redis/archive/7.2.5/redis-7.2.5.tar.gz
        curl -L ${DOWNLOADURL} | tar xz --strip-components=1

        set +ex

    - name: make
      run: |
        make CFLAGS="-static" LDFLAGS="-static"

    - name: store build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          src/redis-cli
          src/redis-sentinel
          src/redis-server

    - name: Release (if tagged)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          src/redis-cli
          src/redis-sentinel
          src/redis-server
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

